### ISSUE TITLE
setup.py indicates the wrong license

### ISSUE THREAD

**Issue by uwerat** [PierreRaybaut/python-qwt#14]
Please fix the license information given in the setup method: the current implementation states being the LGPL - but in fact the "python-qwt" module has some sort of combination between MIT and Qwt license.

PS: you are closing issues too early, what makes it impossible for me to respond ( f.e to piccas questions ).

**Comment by PierreRaybaut** [comment]
I didn't know if it was acceptable to add more than on classifier regarding the license in setup.py but let's give it a try (any consequence on python-stdeb?).

BTW, I can't state "Qwt license" because it has to be in Python classifiers list (that's why I chose "LGPL": after all, the Qwt License is basically LGPL). So, what I can do is add MIT to the list.

But, let's not forget that the only legal license informations are those included in the package itself: LICENSE file and each file's header.

Ok for you?

**Comment by PierreRaybaut** [comment]
I'll take your silence as a yes (it's a less important issue than the other one that is still opened).
