### ISSUE TITLE
fix the license and copyright !

### ISSUE THREAD

**Issue by uwerat** [PierreRaybaut/python-qwt#4]
Translating the Qwt C++ code into python 1:1 doesn't allow you to change the license - the Qwt license of the original code is still very valid and any user of your python translation has to obtain its rules !

More serious the copyright: the Qwt code is my intellectual property and you can't claim being the author + having the copyright  for doing a translation. This is completely unacceptable.

Please fix copyright and license of your project now !

Uwe

PS: please don't use the name Qwt for your project: this is not the Qwt project !

**Comment by PierreRaybaut** [comment]
Hi,

Nice to meet you too and thank you for your kind words.

This is just an alpha version of the library: the license terms are really not that formal or even finalized. Note that I haven't done much publicity around it too. Actually there is no official release, not yet. Every part of the code (including the license which is a dumb copy/paste) is still in a very preliminary state.

No one would assume that I claim the intellectual property of it... Everyone knows that I haven't wrote the original C++ code. Of course. This copyright is just a copy/paste of the copyright from another project (which undoubtedly belongs to me).

You may be the first to read the license. So thank you for pointing out this axis of improvement and sorry for any inconvenience that it may have cause to you when exploring the code...

Regarding the "qwt" name itself, I'm not seeing the legal foundation of your request. Is it reserved somehow?

Best regards,
Pierre Raybaut

Envoyé à partir de mon Windows Phone
________________________________
De : uwerat<mailto:notifications@github.com>
Envoyé : ‎26/‎08/‎2015 21:16
À : PierreRaybaut/qwt<mailto:qwt@noreply.github.com>
Objet : [qwt] fix the license and copyright ! (#4)

Translating the Qwt C++ code into python 1:1 doesn't allow you to change the license - the Qwt license of the original code is still very valid and any user of your python translation has to obtain its rules !

More serious the copyright: the Qwt code is my intellectual property and you can't claim being the author + having the copyright  for doing a translation. This is completely unacceptable.

Please fix copyright and license of your project now !

Uwe

PS: please don't use the name Qwt for your project: this is not the Qwt project !

---
Reply to this email directly or view it on GitHub:
https://github.com/PierreRaybaut/qwt/issues/4

**Comment by stonebig** [comment]
If I understand well Uwe expectations, the request are:
* to put a sticker in the coming licence.
````
           [program/widget] is based in part on the work of
           the Qwt project (http://qwt.sf.net).
````
* to rename the project to something different, 'Qwt.py' for example ?

**Comment by PierreRaybaut** [comment]
The commit above is just a first step towards the right direction I hope.
Would you have another suggestion?

**Comment by uwerat** [comment]
Hi Pierre,

your translation into python is like a fork: you have rights on what you did after the fork only, but you are not allowed to remove my copyright or to change the license without my permission. So once you have added my copyright and the Qwt license ( both are valid for any user of your project ) you are back on a legal path.

Note that the copyright has to be clear ( it can't be none ! ) as the holder is allowed to decide about licenses and f.e. I don't want to allow you ( or anyone else ) to sell special versions of my work under commercial licenses.

How to protect your part of the project is then up to you as long as it doesn't conflict with the Qwt license. But whatever you decide: a project like guiqwt will be affected by the Qwt license in the same way as when using  PyQwt bindings - beside that Gerards copyright and license will be obsolete.

Please don't get me wrong: I don't want to hinder your project, but consider someone would re-translate "your" code back into C++ - where would be my copyright then ?

Concerning the name: some name that contains "qwt" is fine, but using "qwt" instead of "Qwt" doesn't make too much sense. But in opposite to the copyright/license issue I don't care about it much.

ciao,
Uwe

**Comment by PierreRaybaut** [comment]
Hi Uwe,

I have the feeling that we got off on the wrong foot yesterday and I'm mostly responsible for that, because I was not in a very good mood for other reasons which have nothing to do with you or with the project. So please accept my apologies if the beginning of my first answer was a little bit ironic. I fully understand your original request and the excessive use of exclamation marks :-).
I hope that you also have understood that it was not my intention to steal anything from you (I have done a lot of purely philantropic work around Python for a while now...) and that the license terms you read were not intended to be the final version included in the first official release. It was just a copy/paste from another project (I tend to spend more time on writing code than on protecting myself from a legal point of view which is wrong I know). I probably should have wait for a finalized version of the license terms before sharing the project on GitHub but it was so obvious to me that everything is in this project was a work in progress that I did not wait for it.

Anyway, now is the time to fix things and move forward, so I made a few changes on the license terms in PR https://github.com/PierreRaybaut/python-qwt/pull/5.

And I have renamed the project into "python-qwt" to avoid any confusion with your project (even if Python and C++ are two different worlds).

What do you think about it?

Cheers,
-Pierre

**Comment by uwerat** [comment]
Hi Pierre,

I crossed your project when reading https://ftp-master.debian.org/new/python-qwt_6.1.2~a3-1~exp1.html. I can also see, that you have already released a version of guiqwt, that requires your python port. So IMO this is beyond having put something to github - it is already in the public ( I consider setting some exclamation marks to indicate, that I expect seeing this all fixed right now is a moderate reaction ).

To be explicit about what I expect: the Qwt license ( as being derived from the LGPL ) requires naming a holder of the copyright and this is me. So wherever there is a copyright notice you have to replace your name by mine. You also have to remove all statements indicating that the MIT license might rule and replace it by the Qwt license. As far as I can see both issues affects almost all files of your project.

Next I expect that you recall all software that has been published with the wrong copyright/license - at least by releasing a new version with a correct one: as soon as possible !

Please understand that I'm as uninterested in all this licenses stuff as you are and I leave it up to you to read the Qwt license to understand what you are allowed to do to protect your work ( guess you don't want to allow me to sell the python port under a commercial license either ). But with whatever you come up with: I don't permit to change the license or to remove my copyright.

Once this has been done please contact me per Email so that we can discuss in a more relaxed way how to set up the project in a way you can live with.

ciao,
Uwe

PS: there is an argument against using python-qwt as name, but I don't want to explain them here

**Comment by PierreRaybaut** [comment]
Ok clearly I can't spend one more minute of my free time on this. Despite my efforts to regularize the situation.... hum...  well, I'll remove the project definitely, I suppose you will be ok with that.

Anyway, please leave guiqwt out of it because it has nothing to do with it. It is the Python world here... qwt is imported dynamically but is not included in guiqwt, so there is absolutely no license propagation or whatsoever and that is the most certain thing here.

**Comment by PierreRaybaut** [comment]
Project has been removed from https://pypi.python.org/pypi.

**Comment by PierreRaybaut** [comment]
I have removed all the alpha versions on PyPI (by the way, did you know the meaning of an alpha version? as well as the meaning of a "honest mistake" or "benefit of the doubt" ? ;-) ).
And there are no more copyrights too. (I forgot about the file headers, so that's fixed too)
So, everything you asked is done. I'm closing the issue.
